version: 2.0.0.{build}

skip_tags: true

cache:
  - packages -> **\packages.config

before_build:
  - cmd: nuget restore XMLUnit.NET.sln
  - cmd: git submodule update --init

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

notifications:
  - provider: Email
    to:
      - xmlunit-commits@lists.sourceforge.net
    on_build_status_changed: true
    on_build_failure: true
