version: 2.0.0.{build}

skip_tags: true

cache:
  - packages -> **\packages.config

install:
  - cmd: git submodule update --init
  - cmd: nuget restore XMLUnit.NET.sln

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

notifications:
  - provider: Email
    to:
      - xmlunit-commits@lists.sourceforge.net
    on_build_status_changed: true
    on_build_failure: true

# tests are already run during build phase
test: off
